#!/bin/bash
mkdir /dev/net && mknod /dev/net/tun c 10 200
iptables -t nat -C POSTROUTING -s 10.8.0.0/30 -o eth0 -j MASQUERADE ||
iptables -t nat -A POSTROUTING -s 10.8.0.0/30 -o eth0 -j MASQUERADE
cd /etc/openvpn
openvpn server.conf
